name: df_http
description: "Flutter networking helper package that extends the official http client with built-in retries, token refresh, and request/response processing for easier API integration."

version: 2.0.0

homepage: https://dartforce.dev/
repository: https://github.com/DartForce22/df_http.git
license: MIT

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^4.3.9
    
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:

  uses-material-design: true